### ISSUE TITLE
FRQ ・ Multi-line notes

### ISSUE THREAD

**Issue by Lilafian** [ThatFrogDev/notabena#8]
## Is this a fix to a problem or just a new feature that you'd like to see?
[x] Problem
[ ] New feature

## (optional) For what problem is your feature a fix?
You can only have single-line notes.

## What is the solution or feature?
Make it so that notes can be multiline.

An idea is to make it so Shift+Enter creates a newline, or even an entire new editing mode.

**Comment by ThatFrogDev** [comment]
We are looking into that. Stay tuned for the next CLI release! 👀

**Comment by MrSerge01** [comment]
sometime soon™ 👀

**Comment by SwiftDust** [comment]
Couldn't be bothered doing this for now since we're probably moving away from the current codebase. Will possibly be re-opened when we know more. (https://discord.com/channels/1178803368806842408/1178813526958162001/1179414477175799909 for more information)

**Comment by SwiftDust** [comment]
This is planned somewhere in the future.
